version: '3.7'
services:
  influxdb:
    image: signalk:influxdb
    container_name: influxdb
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb:Z
    command: influxd
    network_mode: host
  couchdb:
    build: docker/couchdb
    container_name: couchdb
    ports:
      - 5984:5984
    volumes:
      - ./docker/couchdb/data:/opt/couchdb/data
    network_mode: host